//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VendingMachine.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public string TradeNo { get; set; }
        public string Machine_ID { get; set; }
        public string SlotNo { get; set; }
        public Nullable<int> MsgType { get; set; }
        public string Product_ID { get; set; }
        public System.DateTime Time { get; set; }
        public bool Status { get; set; }
        public int FunCode { get; set; }
        public string ErrorMsg { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string UpdateJson { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Slot Slot { get; set; }
    }
}
